// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm1AM_qMEJxZM81h0dMXLoCXFObGWZtEw',
    appId: '1:561710958040:web:db5358fe2588901c4adead',
    messagingSenderId: '561710958040',
    projectId: 'brew-crew-c64cf',
    authDomain: 'brew-crew-c64cf.firebaseapp.com',
    storageBucket: 'brew-crew-c64cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIawH0S0YRoO8oDM3RwC_mzeOx10nAGyw',
    appId: '1:561710958040:android:23c6ae738f60a6114adead',
    messagingSenderId: '561710958040',
    projectId: 'brew-crew-c64cf',
    storageBucket: 'brew-crew-c64cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOs-ZkwGIkwq1nkNyTO7verKx4ZW6_LpY',
    appId: '1:561710958040:ios:5486b0c2a33beb6f4adead',
    messagingSenderId: '561710958040',
    projectId: 'brew-crew-c64cf',
    storageBucket: 'brew-crew-c64cf.appspot.com',
    iosClientId: '561710958040-t8tvt7bmpr2kmpjp83il6o9svrf6vqg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOs-ZkwGIkwq1nkNyTO7verKx4ZW6_LpY',
    appId: '1:561710958040:ios:5486b0c2a33beb6f4adead',
    messagingSenderId: '561710958040',
    projectId: 'brew-crew-c64cf',
    storageBucket: 'brew-crew-c64cf.appspot.com',
    iosClientId: '561710958040-t8tvt7bmpr2kmpjp83il6o9svrf6vqg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
